name: Pubslish Main NPM Package to NPM and GPR

on:
  release:
      types: [created]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: echo "Build"

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://registry.npmjs.org"
            - run: npm install
            - run: npm publish --access=public --tag 1.3.x-latest
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@quantalabs"
            - run: npm install
            - run: echo "registry=https://npm.pkg.github.com/@quantalabs" >> .npmrc
            - run: npm publish --access=public --tag 1.3.x-latest
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
