name: Pubslish Main NPM Package to NPM and GPR

on:
  workflow_dispatch:
    inputs:
      tag: 
        description: 'Tag to use'
        required: false
        default: 'latest'

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://registry.npmjs.org"
            - run: npm publish --access=public --tag=${{ github.event.inputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@epispot"
            - run: echo "registry=https://npm.pkg.github.com/@epispot" >> .npmrc
            - run: npm publish --access=public --tag=${{ github.event.inputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}